<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KCLRGFN" ignored="0" name="M01" tests="1" failures="1" timestamp="25 Jan 2019 22:08:37 GMT" time="0.031" errors="0">
  <testcase name="TC01_Login" time="0.0" classname="m01_2019.Sprint1.Tests">
    <failure type="org.testng.TestNGException" message="
Cannot instantiate class DataUtilities.DataProviderMethod">
      <![CDATA[org.testng.TestNGException: Cannot instantiate class DataUtilities.DataProviderMethodat org.testng.internal.ClassHelper.newInstance(ClassHelper.java:71)at org.testng.internal.Parameters.findDataProvider(Parameters.java:582)at org.testng.internal.Parameters.findDataProvider(Parameters.java:509)at org.testng.internal.Parameters.handleParameters(Parameters.java:691)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.InstantiationException: DataUtilities.DataProviderMethodat java.lang.Class.newInstance(Class.java:427)at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)... 23 moreCaused by: java.lang.NoSuchMethodException: DataUtilities.DataProviderMethod.<init>()at java.lang.Class.getConstructor0(Class.java:3082)at java.lang.Class.newInstance(Class.java:412)... 24 more]]>
    </failure>
  </testcase> <!-- TC01_Login -->
</testsuite> <!-- M01 -->
